baseURL = "https://example.com/"
title = "CIPAL ONLINE"
author = "CIPAL"
copyright = "GPL-3.0 license"
paginate = 10
languageCode = "es"
defaultContentLanguage = "es"
theme = "tailwind"

[params]
  contentTypeName = "posts"

  [params.header]
    logo = "img.png"

  [params.footer]
    since = 2024
    poweredby = true

  [params.social_media]

    [[params.social_media.items]]
      enabled = true
      title = 'Github'
      icon = 'brand-github'
      link = 'https://github.com/cipalonline/cipalonline.github.io'

[menu]

  [[menu.main]]
    identifier = "about"
    name = "Sobre nosotros"
    pageRef = "/about.md"
    weight = 0

  [[menu.main]]
    identifier = "post"
    name = "Post"
    pageRef = "/posts"
    weight = 1

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

